name: Deploy frontend service to Google Cloud Run

on:
  push:
    branches:
      - master
    paths:
      - 'frontend/**'

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: frontend
  IMAGE: ${{ secrets.FRONTEND_IMAGE }}

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Authorize Docker push to Google Artifact Registry
        run: gcloud auth configure-docker ${{ secrets.GCP_FRONTEND_ARTIFACT }}

      - name: Build and push Docker image
        run: |
          echo "NEXT_PUBLIC_API_BASE_URL=${{ vars.API_BASE_URL }}" > ./frontend.env.local
          docker build -t $IMAGE:${{ github.sha }} ./frontend
          docker push $IMAGE:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image $IMAGE:${{ github.sha }} \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated 
